// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3NS7ZfY8abRoivKRF0OBDOOqsdvSyqfQ',
    appId: '1:889435964698:web:635f5695aae7a3f2f518a3',
    messagingSenderId: '889435964698',
    projectId: 'test-356b2',
    authDomain: 'test-356b2.firebaseapp.com',
    storageBucket: 'test-356b2.firebasestorage.app',
    measurementId: 'G-C6GH7TDTSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnTJG8hSDV-lsW2aBqMU2K0uEPozGWfTM',
    appId: '1:889435964698:android:26dc085f35d76f56f518a3',
    messagingSenderId: '889435964698',
    projectId: 'test-356b2',
    storageBucket: 'test-356b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBj_yorbv3YuBM-VMgNoZyWpPaqB_bcl0',
    appId: '1:889435964698:ios:1b5c872d0a989e91f518a3',
    messagingSenderId: '889435964698',
    projectId: 'test-356b2',
    storageBucket: 'test-356b2.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBj_yorbv3YuBM-VMgNoZyWpPaqB_bcl0',
    appId: '1:889435964698:ios:1b5c872d0a989e91f518a3',
    messagingSenderId: '889435964698',
    projectId: 'test-356b2',
    storageBucket: 'test-356b2.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeEWD16-vAihMmDP3Ju9tyZi0IhnsyFCE',
    appId: '1:889435964698:web:a0008ae7506f291cf518a3',
    messagingSenderId: '889435964698',
    projectId: 'test-356b2',
    authDomain: 'test-356b2.firebaseapp.com',
    storageBucket: 'test-356b2.firebasestorage.app',
    measurementId: 'G-J3QKY83MRC',
  );
}
